[project]
name = "sieveofatkin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitarray>=3.0.0",
]

[tool.ruff]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = [
    "D",
    "N",
    "PTH",
]

[dependency-groups]
dev = [
    "git-cliff>=2.7.0",
]
